### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by minamijoyo**
```
[docker-ecs-goploy@add-dockerfile|✔]$ docker build -t ecs-goploy --no-cache .
Sending build context to Docker daemon  66.56kB
Step 1/6 : FROM alpine:3.9 AS builder
 ---> 5cb3aa00f899
Step 2/6 : ENV ECS_GOPLOY_VERSION=v0.5.0
 ---> Running in 20154dbc9555
Removing intermediate container 20154dbc9555
 ---> ed3b4d935897
Step 3/6 : RUN wget https://github.com/h3poteto/ecs-goploy/releases/download/${ECS_GOPLOY_VERSION}/ecs-goploy_${ECS_GOPLOY_VERSION}_linux_amd64.zip   && unzip -d /usr/local/bin/ ecs-goploy_${ECS_GOPLOY_VERSION}_linux_amd64.zip
 ---> Running in a7cef341b2aa
Connecting to github.com (192.30.255.113:443)
Connecting to github-production-release-asset-2e65be.s3.amazonaws.com (52.216.170.235:443)
ecs-goploy_v0.5.0_li   2% |                                |  135k  0:00:34 ETA
ecs-goploy_v0.5.0_li  67% |*********************           | 3206k  0:00:00 ETA
ecs-goploy_v0.5.0_li 100% |********************************| 4778k  0:00:00 ETA

Archive:  ecs-goploy_v0.5.0_linux_amd64.zip
  inflating: ecs-goploy
Removing intermediate container a7cef341b2aa
 ---> d1b24aeeb865
Step 4/6 : FROM alpine:3.9
 ---> 5cb3aa00f899
Step 5/6 : COPY --from=builder /usr/local/bin/ecs-goploy /usr/local/bin/ecs-goploy
 ---> 48c8518d41c1
Step 6/6 : ENTRYPOINT ["ecs-goploy"]
 ---> Running in 5f3d6756c58e
Removing intermediate container 5f3d6756c58e
 ---> 38b16c04434a
Successfully built 38b16c04434a
Successfully tagged ecs-goploy:latest
```

### CODE REVIEW

**Review by tmknom — APPROVED** [review]
LGTM 👍

**Review by kangaechu — APPROVED** [review]
LGTM 👍

**Comment by sawadashota** [comment]
Awesome!

**Review by sawadashota — APPROVED** [review]
Awesome!

**Comment by minamijoyo** [comment]
Thanks!
Ship it :shipit:

**Pull request merged**
